from setuptools import setup

setup(
    name='SmarTrash',
    version='',
    packages=['venv.lib.python3.6.site-packages.js.json', 'venv.lib.python3.6.site-packages.cv2',
              'venv.lib.python3.6.site-packages.cv2.data', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pep517',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.cli',
              'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.numpy', 'venv.lib.python3.6.site-packages.numpy.ma',
              'venv.lib.python3.6.site-packages.numpy.ma.tests', 'venv.lib.python3.6.site-packages.numpy.doc',
              'venv.lib.python3.6.site-packages.numpy.fft', 'venv.lib.python3.6.site-packages.numpy.fft.tests',
              'venv.lib.python3.6.site-packages.numpy.lib', 'venv.lib.python3.6.site-packages.numpy.lib.tests',
              'venv.lib.python3.6.site-packages.numpy.core', 'venv.lib.python3.6.site-packages.numpy.core.tests',
              'venv.lib.python3.6.site-packages.numpy.f2py', 'venv.lib.python3.6.site-packages.numpy.f2py.tests',
              'venv.lib.python3.6.site-packages.numpy.tests', 'venv.lib.python3.6.site-packages.numpy.compat',
              'venv.lib.python3.6.site-packages.numpy.compat.tests', 'venv.lib.python3.6.site-packages.numpy.linalg',
              'venv.lib.python3.6.site-packages.numpy.linalg.tests', 'venv.lib.python3.6.site-packages.numpy.random',
              'venv.lib.python3.6.site-packages.numpy.random.tests', 'venv.lib.python3.6.site-packages.numpy.testing',
              'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.webob',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.requests', 'venv.lib.python3.6.site-packages.fanstatic',
              'venv.lib.python3.6.site-packages.websocket', 'venv.lib.python3.6.site-packages.websocket.tests',
              'venv.lib.python3.6.site-packages.shutilwhich', 'venv.lib.python3.6.site-packages.watson_developer_cloud',
              'venv.lib.python3.6.site-packages.watson_developer_cloud.websocket',
              'venv.lib.python3.6.site-packages.watson_developer_cloud.natural_language_understanding',
              'venv.lib.python3.6.site-packages.watson_developer_cloud.natural_language_understanding.features',
              'venv.lib.python3.6.site-packages.watson_developer_cloud.natural_language_understanding.features.v1'],
    url='',
    license='',
    author='Adam, Lorenzo, Valentine',
    author_email='',
    description=''
)
